routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::get('locale/{locale}', 'Shop\MainController@changeLocale')->name('locale');
Route::get('currency/{currencyCode}', 'Shop\MainController@changeCurrency')->name('currency');


Route::middleware(['set_locale'])->group(function () {
    Route::get('reset', 'ResetController@reset')->name('reset');
    Route::middleware(['auth'])->group(function () {
        Route::group([
            'prefix' => 'person',
            'namespace' => 'Shop\Person',
            'as' => 'person.',
        ], function () {
            Route::get('/orders', 'OrderController@index')->name('orders.index');
            Route::get('/orders/{order}', 'OrderController@show')->name('orders.show');
        });

        Route::group([
            'namespace' => 'Shop\Admin',
            'prefix' => 'Admin',
        ], function () {
            Route::group(['middleware' => 'is_admin'], function () {
                Route::get('/orders', 'OrderController@index')->name('home');
                Route::get('/orders/{order}', 'OrderController@show')->name('orders.show');
            });

            Route::resource('categories', 'CategoryController');
            Route::resource('products', 'ProductController');
            Route::resource('products/{product}/skus', 'SkuController');
            Route::resource('properties','PropertyController');
            Route::resource('merchants','MerchantController');
            Route::get('merchant/{merchant}/update_token', 'MerchantController@updateToken')->name('merchants.update_token');
            Route::resource('properties/{property}/property-options','PropertyOptionController');
            Route::resource('coupons','CouponController');
        });
    });


    Route::group(['namespace' => 'Shop'], function () {
        Route::get('/', 'MainController@index')->name('index');
        Route::get('categories', 'MainController@categories')->name('categories');
        Route::post('subscription/{sku}', 'MainController@subscribe')->name('subscription');

        // Корзина товаров
        Route::middleware(['auth'])->group(function () {
            Route::group(['prefix' => 'basket'], function () {
                Route::post('/add/{sku}', 'BasketController@basketAdd')->name('basket-add');

                Route::group(['middleware' => 'basket_not_empty',], function () {
                    Route::get('/', 'BasketController@basket')->name('basket');
                    Route::get('/place', 'BasketController@basketPlace')->name('basket-place');
                    Route::post('/remove/{sku}', 'BasketController@basketRemove')->name('basket-remove');
                    Route::post('/place', 'BasketController@basketConfirm')->name('basket-confirm');
                    Route::post('coupon', 'BasketController@setCoupon')->name('set-coupon');
                });
            });
        });

        Route::get('{category}', 'MainController@category')->name('category');
        Route::get('{category}/{product}/{sku}', 'MainController@sku')->name('sku');
    });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@admin @lang('admin.admin_title'): @endadmin @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">


                    <!-- Right Side Of Navbar -->
{{--                    <ul class="navbar-nav ml-auto">--}}
                        <ul class="nav navbar-nav">
                            <!-- Authentication Links -->
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('index') }}">@lang('main.back_to_site')</a>
                            </li>
                        @admin
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('categories.index') }}">@lang('admin.title.categories_title')</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('products.index') }}">@lang('admin.title.products_title')</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('properties.index') }}">@lang('admin.title.properties_title')</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('coupons.index') }}">Купоны</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('home') }}">@lang('admin.title.orders_title')</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('merchants.index') }}">Поставщики</a>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item"><a class="nav-link" href="{{ route('locale', __('main.set_lang')) }}">@lang('main.set_lang')</a></li>
                        @endadmin
                        @authnotadmin
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('basket') }}">@lang('admin.title.orders_title')</a>
                        </li>
                        @endauthnotadmin
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Войти') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Регистрация') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                   @admin Администратор @else {{ Auth::user()->name }} @endadmin
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        @lang('main.logout')
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        </ul>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@lang('main.online_shop'): @yield('title')</title>

    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
    <script src="/js/app.js"></script>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link href="/css/starter-template.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ route('index') }}">@lang('main.online_shop')</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li @routeactive('index')><a href="{{ route('index') }}">@lang('main.all_products')</a></li>
                <li @routeactive('categor*')><a href="{{ route('categories') }}">@lang('main.categories')</a></li>
                <li @routeactive('basket*')><a href="{{ route('basket') }}">@lang('main.your_cart')</a></li>
                <li><a href="{{ route('reset') }}">@lang('main.reset_project_to_default_state')</a></li>
                <li><a href="{{ route('locale', __('main.set_lang')) }}">@lang('main.set_lang')</a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ $currencySymbol }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                       @foreach($currencies as $currency)
                            <li><a href="{{ route('currency', $currency->code) }}">{{ $currency->symbol }}</a></li>
                           @endforeach
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
            @auth
                @admin
                    <li><a href="{{ route('home') }}">@lang('admin.admin_panel')</a></li>
                @else
                    <li><a href="{{ route('person.orders.index') }}">@lang('main.my_orders')</a></li>
                    @endadmin
                    <li><a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        @lang('main.logout')
                        </a></li>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">

                        @csrf
                    </form>
                </ul>
            @endauth
            @guest
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ route('login') }}">@lang('main.login')</a></li>
                <li><a href="{{ route('register') }}">@lang('main.register')</a></li>
            </ul>
            @endguest
        </div>
    </div>
</nav>
<main class="py-4 content">
    <div class="container content">
        <div class="starter-template">
            @if(session()->has('success'))
                <p class="alert alert-success cc_cursor">{{ session()->get('success') }}</p>
            @endif
                @if(session()->has('warning'))
                    <p class="alert alert-warning cc_cursor">{{ session()->get('warning') }}</p>
            @endif
            @yield('content')
        </div>
    </div>
</main>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6"><p>Категории товаров</p>
                <ul>
                    @foreach($categories as $category)
                        <li><a href="{{ route('category', $category->code) }}">{{ $category->__('name') }}</a></li>
                    @endforeach
                </ul>
            </div>
            <div class="col-lg-6"><p>Самые популярные товары</p>
                <ul>
                    @foreach($bestSkus as $bestSku)
                        <li><a href="{{ route('sku', [$bestSku->product->category->code,
                        $bestSku->product->code, $bestSku]) }}">{{ $bestSku->product->__('name') }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
</footer>

</body>
</html>